<a href="https://colab.research.google.com/github/aayushinidhi/Aayushi-Saxena/blob/main/Lecture_4_Slicing_%2CStacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Slicing





In [1]:
import numpy as np

In [3]:
a=np.array([6,7,8,9]) # passing a list to an array
a

array([6, 7, 8, 9])

In [6]:
a[0:2] # starting from 0 and will go till n-1 i.e.2-1=1 index

array([6, 7])

In [5]:
a[2:4]

array([8, 9])

In [8]:
a[2:] # starting from index 2 and go till end

array([8, 9])

In [10]:
print(a[-1])

9


In [11]:
print(a[-2:])

[8 9]


In [14]:
b=np.array([[1,2,3],
            [4,5,6],
            [7,8,9] ]) # passing a 2-D list to an array
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(b[1,2])

6


In [19]:
print(b[2,0])

7


In [21]:
b[-1] # for 2-D array -1 index will give the last row

array([7, 8, 9])

In [22]:
print(b[-1,0])

7


In [23]:
print(b[-1,1])

8


In [25]:
# To Print first 2 elements of last row
print(b[-1,0:2])

[7 8]


In [27]:
# To print 2nd an 3rd column
b[:,1:3] # means i want all the three rows and 2nd and 3rd column


array([[2, 3],
       [5, 6],
       [8, 9]])

# Stacking


**For combining two numpy array we have horizontal stacking and vertical stacking.**

**hstack()**

-Is used to horizontally stack arrays i.e. along axis=1

In [32]:
# Customer ID , Nmae
c=np.array([[101,'Mira'],
            [102,'Abdul'],
            [103,'Andrea']])
# Customer ID, Purchase Amount ,Purchase Date
d=np.array([
    [101,250.50,'2023-08-01'],
    [102,150.00,'2023-08-02'],
    [103, 300.75,'2023-08-93']
])

np.hstack((c,d)) # horizontal stacking and the 2 numpy arrays are passed as a tuple

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-93']], dtype='<U32')

**vstack()**

In [35]:
c=np.array([[101,'Mira'],
            [102,'Abdul'],
            [103,'Andrea']])
d=np.array([[104 ,'Venkat'],
            [105,'David'],
            [105,'Aryan']])
np.vstack((c,d)) # vertical stacking along axis=0

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'David'],
       ['105', 'Aryan']], dtype='<U21')

# Spliting

**A numpy array can be split into multiple sub-arrays using horizontal and vertical spliting**

**hsplit()**

-Split an array into multiple sub-arrays horizontally (column-wise) i.e. along axis=1

In [39]:
transactions=np.array([
    [101,'Mohan',250.50,'2023-08-01'],
    [102,'Bob',150.00,'2023-08-02'],
    [103,'Fatima',300.75,'2023-08-01'],
    [104,'David',400.20,'2023-08-03'],
    [105,'Aryan',330.1,'2023-08-04']

])
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [42]:
x,y=np.hsplit(transactions,[2]) # split along columns(axis=1) .Here [2]-->column index
x

array([['101', 'Mohan'],
       ['102', 'Bob'],
       ['103', 'Fatima'],
       ['104', 'David'],
       ['105', 'Aryan']], dtype='<U32')

In [41]:
y

array([['250.5', '2023-08-01'],
       ['150.0', '2023-08-02'],
       ['300.75', '2023-08-01'],
       ['400.2', '2023-08-03'],
       ['330.1', '2023-08-04']], dtype='<U32')

**vsplit()**

-Split an array into multiple sub-arrays vertically(row-wise) i.e. along axis=0

In [43]:
transactions=np.array([
    [101,'Mohan',250.50,'2023-08-01'],
    [102,'Bob',150.00,'2023-08-02'],
    [103,'Fatima',300.75,'2023-08-01'],
    [104,'David',400.20,'2023-08-03'],
    [105,'Aryan',330.1,'2023-08-04']

])
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [45]:
w,z=np.vsplit(transactions,[2]) # split from row 2
w

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')

In [46]:
z

array([['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

# Masking

-Used for filtering values in numpy array.

-There are two ways to carry out boolean masking-

**1) Returning the result array**

**2) Returning a boolean array**

**Returning The Result Array**

-condition in indexing bracket [] of an array an it returns an array with required result

In [48]:
# Method 1: Returning the result array

m=np.arange(15)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
m[m>5] # Here we pass a condition in indexing bracket [] of an array an it returns an array with required result

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
m[m%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

**Returning The Boolean Array**

-Returns a  boolean array of same size as the array it represents.

-The boolean array only contains value of either True or False

-The boolean array is called mask array or simple mask

In [53]:
m1=np.arange(20)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
mask=m1>8
print(mask)

[False False False False False False False False False  True  True  True
  True  True  True  True  True  True  True  True]


In [56]:
m1[mask] # the mask array can be passed in the index brackets of arr to return values that satisfy the condition.

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
monthly_sales=np.array([30,33,35,28,42])
monthly_sales

array([30, 33, 35, 28, 42])

In [63]:
result=monthly_sales<32
result

array([ True, False, False,  True, False])

In [65]:
monthly_sales[result]  # 30 and 28 are the two sales values that are less than the threshold 32

array([30, 28])

# argmax()

-Returns the indices of the maximum values along an axis.

In [66]:
monthly_sales=np.array([30,33,35,28,42])
monthly_sales

array([30, 33, 35, 28, 42])

In [71]:
print(np.max(monthly_sales))




42


In [87]:
index=np.argmax(monthly_sales)
print(index)

4


In [91]:
print(monthly_sales[index]) # To get the value back


42


For 2-D array

In [76]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])
arr


array([[10, 20, 30],
       [40, 50, 60]])

In [79]:
print(np.max(arr))

60


In [80]:
print(np.argmax(arr)) #  For a 2D array, it flattens the array by default and returns the index as if it's a 1D array.

5


In [81]:
# To get the row index (axis=0)
print(np.argmax(arr,axis=0)) #from [[10, 20, 30],
                             #[40, 50, 60]] -->40 ,50,60 are max values along axis=0 and indexes of these three are [1 1 1]

[1 1 1]


In [85]:
print(np.argmax(arr,axis=1)) #from [[10, 20, 30],
                             #[40, 50, 60]] --->30 and 60 are max values along axis=1 and hence has index [2 2]

[2 2]


In [119]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [124]:
# To find the maximum value of tansaction and index corresponding to it
# Max value is 400.2 by david
max_index=np.argmax(transactions[:,2].astype(float))
print(max_index)

3


In [125]:
transactions[max_index]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [128]:
transactions[transactions[:,0]=='102'] # passing a condition

array([['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')

# Type Conversion

1) astype()

2) dtype()

In [107]:
a=np.array([6,7,8,9]) # passing a list to an array
a

array([6, 7, 8, 9])

In [106]:
# Method 1:
a.astype(float) # converting from one data type to another using astype and dtype


array([6., 7., 8., 9.])

In [108]:
# Method 2
a=np.array([6,7,8,9],dtype=np.float64) # passing a list to an array
a

array([6., 7., 8., 9.])

# To extract a particular colum from 2-D array

In [109]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [112]:
# To extract all the ids
print(transactions[:,0])

['101' '102' '103' '104' '105']


# Fancy Indexing

It means to access multiple array elements at once

In [129]:
m3=np.array([2,4,7,8,9,11,12,15,19,23])
print(m3)


[ 2  4  7  8  9 11 12 15 19 23]


In [131]:
print(m3[1]) # to access a single element

4


In [132]:
m3[[1,4,9,5,2,1,1]] # passing a list of indices whose values we want to know

array([ 4,  9, 23, 11,  7,  4,  4])